# 100 numpy

 <https://github.com/rougier/numpy-100>.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__

'1.20.3'

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [4]:
print("Size of the array:", a.size)
print("Memory size of one array element in bytes:", a.itemsize)
print("Memory size of numpy array in bytes:", a.size*a.itemsize)

Size of the array: 10
Memory size of one array element in bytes: 8
Memory size of numpy array in bytes: 80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
b = np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
np.flip(b)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [14]:
c = np.arange(0,9)
print(c)
c.reshape(3, 3)

[0 1 2 3 4 5 6 7 8]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [20]:
d = [1,2,0,0,4,0]
p = np.nonzero(d)
p
# nz = np.nonzero([1,2,0,0,4,0])
# print(nz)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [94]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [23]:
np.random.random((3,3,3))

array([[[0.29503788, 0.00854827, 0.11230671],
        [0.72247037, 0.07914192, 0.51169646],
        [0.43143689, 0.57366121, 0.3679929 ]],

       [[0.57384096, 0.6013605 , 0.49479124],
        [0.90330398, 0.41651517, 0.02170461],
        [0.64423918, 0.99735755, 0.3169725 ]],

       [[0.08424834, 0.44079826, 0.26017727],
        [0.14782866, 0.43494551, 0.26875103],
        [0.23237177, 0.94911239, 0.01766381]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [34]:
c = np.random.random((10, 10))
c.min()
c.max()
print(c)
print(c.min(), c.max())

[[0.03418381 0.62385149 0.12654052 0.43306745 0.21073162 0.82918661
  0.72958959 0.35188817 0.84224601 0.54625462]
 [0.77485457 0.07173696 0.19510737 0.80176289 0.55963745 0.82919109
  0.44186625 0.07508313 0.1321203  0.54530099]
 [0.54764632 0.54115186 0.99865473 0.69538552 0.02451416 0.09425792
  0.38949158 0.20199022 0.53297939 0.91264728]
 [0.60027993 0.38675344 0.24432979 0.71684787 0.07191893 0.38933905
  0.3525075  0.4248845  0.68472905 0.72065574]
 [0.59950862 0.02490985 0.24414914 0.01891977 0.14111654 0.97548414
  0.27797455 0.34553319 0.69140523 0.0336957 ]
 [0.94714577 0.58808507 0.44545109 0.54238971 0.93650187 0.8329901
  0.18838917 0.32105152 0.03213326 0.94051003]
 [0.22043451 0.30148825 0.38510368 0.20650994 0.65030097 0.16760297
  0.36953504 0.78511774 0.68934582 0.20569439]
 [0.02287724 0.11465834 0.65917751 0.31172979 0.81258371 0.01510791
  0.68214096 0.50778964 0.951814   0.95090036]
 [0.08960265 0.52460739 0.14305267 0.82406053 0.43933969 0.27613439
  0.08344544 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [36]:
np.random.random((30)).mean()

0.4870434801100643

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [89]:
Z = np.ones((8,6), dtype=int)
Z[1:7,1:5] = 0
print(Z)

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [88]:
d = np.random.random((5,3))
d = np.pad(d, pad_width=1)
d

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.27380878, 0.68447982, 0.96015982, 0.        ],
       [0.        , 0.24925053, 0.92437687, 0.59513836, 0.        ],
       [0.        , 0.82046194, 0.82553116, 0.55057259, 0.        ],
       [0.        , 0.92147661, 0.49996056, 0.9385663 , 0.        ],
       [0.        , 0.84807011, 0.43876755, 0.12701303, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [60]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [105]:
e = np.diag([1, 2, 3, 4], -1)
print(e)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [85]:
d = np.zeros((8,8),dtype=int)
d[::2,::2] = 1
d[1::2,1::2] = 1
print(d)

# arr = np.ones(64,dtype=int)
# arr[::2]=0
# arr = arr.reshape((8,8))
# print(arr)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [113]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [117]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [120]:
Z = np.random.random((5,5))
x = (Z - np.mean (Z)) / (np.std (Z))
print(x)

[[-1.300873   -0.49911378  1.09259777 -1.38641848 -1.10953657]
 [ 1.07023394  0.28954575  1.28866816  0.36795639 -0.73838589]
 [ 1.02118775  1.25657943 -0.28356831  0.30602441  1.55772894]
 [-0.15919339  1.11012037 -1.44883759 -0.68596477 -1.39492264]
 [-0.30105818  0.64968857  1.10499974 -0.27990842 -1.52755021]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [150]:
a= np.arange(15).reshape((5, 3))
b= np.arange(6).reshape((3, 2))
np.dot(a,b)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [159]:
Z = np.arange(15)
Z[(3 < Z) & (Z < 8)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [162]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [171]:
# Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
# Z<Z>Z

array([ 0.,  1.,  2.,  3., -4., -5., -6., -7.,  8.,  9., 10., 11., 12.,
       13., 14.])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [175]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\Asus\AppData\Local\Temp/ipykernel_5092/548293649.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
C:\Users\Asus\AppData\Local\Temp/ipykernel_5092/548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [192]:
a = np.random.randint(11,20,15)
print(a)
b = np.random.randint(0,50,7)
print(b)
print(np.intersect1d(a, b))

[17 12 12 18 17 16 14 16 19 19 17 13 11 14 12]
[41 28 12 15 10  1 16]
[12 16]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

# Suicide mode on
defaults = np.seterr(all="ignore") -->
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [193]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\Asus\AppData\Local\Temp/ipykernel_5092/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [196]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday, today, tomorrow)

2022-10-19 2022-10-20 2022-10-21


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [197]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [209]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [222]:
Z = np.random.uniform(30,80,10)
print(Z)
print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[35.56229853 60.6262738  42.038844   56.12102263 72.05001757 33.9159979
 56.72202544 75.26589745 56.35707556 50.28430884]
[35. 60. 42. 56. 72. 33. 56. 75. 56. 50.]
[35. 60. 42. 56. 72. 33. 56. 75. 56. 50.]
[35. 60. 42. 56. 72. 33. 56. 75. 56. 50.]
[35 60 42 56 72 33 56 75 56 50]
[35. 60. 42. 56. 72. 33. 56. 75. 56. 50.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [235]:
np.tile(np.arange(4, 9), (7,3))

array([[4, 5, 6, 7, 8, 4, 5, 6, 7, 8, 4, 5, 6, 7, 8],
       [4, 5, 6, 7, 8, 4, 5, 6, 7, 8, 4, 5, 6, 7, 8],
       [4, 5, 6, 7, 8, 4, 5, 6, 7, 8, 4, 5, 6, 7, 8],
       [4, 5, 6, 7, 8, 4, 5, 6, 7, 8, 4, 5, 6, 7, 8],
       [4, 5, 6, 7, 8, 4, 5, 6, 7, 8, 4, 5, 6, 7, 8],
       [4, 5, 6, 7, 8, 4, 5, 6, 7, 8, 4, 5, 6, 7, 8],
       [4, 5, 6, 7, 8, 4, 5, 6, 7, 8, 4, 5, 6, 7, 8]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [238]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=int,count=-1)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [245]:
np.random.random(10)
# np.linspace(0,1,11,endpoint=False)[1:]

array([0.47142497, 0.37815007, 0.18606304, 0.21773283, 0.27902299,
       0.56788985, 0.7380382 , 0.70810569, 0.70340248, 0.43345564])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [253]:
a = np.random.random(10)
a.sort()
a

array([0.05039041, 0.29168833, 0.33669821, 0.35884545, 0.57683609,
       0.58141661, 0.70629447, 0.71967651, 0.78464817, 0.83812031])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [257]:
Z = np.arange(40)
np.add.reduce(Z)

780

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [264]:
A = np.random.randint(0,8,5)
B = np.random.randint(3,9,5)
print(A, B)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

[7 3 2 4 3] [8 7 7 6 4]
False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [268]:
g = np.zeros(10)
g.flags.writeable = False
print(g)
g[0] = 1

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [269]:
# didn't understand
z= np.random.random((10,2))
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[0.61832805 0.98011661 1.09735362 0.87144315 0.54647369 0.29172736
 1.13280428 1.22210656 0.93459111 0.68506815]
[1.12983623 0.95121282 0.56967641 1.01676633 0.03521668 0.35337378
 0.62074157 0.68768112 1.32826534 1.03582034]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [290]:
z= np.random.random(10)
print(z)
print(z.max())
z[z.argmax()] = 0
print(z)

[0.73569766 0.68229043 0.60152383 0.19257484 0.46053448 0.19194326
 0.75660076 0.45184695 0.93635684 0.84805612]
0.936356838422004
[0.73569766 0.68229043 0.60152383 0.19257484 0.46053448 0.19194326
 0.75660076 0.45184695 0.         0.84805612]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [293]:
#??????????????????
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [298]:
# np.set_printoptions(threshold=float("inf"))
Z = np.zeros((4,10))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [302]:
Z = np.random.random((10,2))
Z

array([[0.24164906, 0.71137722],
       [0.04437281, 0.76621567],
       [0.96346309, 0.61868522],
       [0.354244  , 0.55415889],
       [0.03274489, 0.95323415],
       [0.37751112, 0.37785972],
       [0.67491644, 0.58375372],
       [0.62823936, 0.87944242],
       [0.50036809, 0.02879815],
       [0.82105585, 0.65385645]])

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [306]:
Z = (np.random.rand(10)*100).astype(np.float32)
print(Z)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[91.3812     50.94431    43.397923    0.59718275 48.358814   94.30615
 30.060808    7.784671   60.837334   74.15676   ]
[91 50 43  0 48 94 30  7 60 74]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [310]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11''')


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [314]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),5)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 0. 0. 5. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [323]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
# Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[-0.26181638 -0.11018901 -0.03685589  0.31302825 -0.16692293  0.0578172
  -0.26549264 -0.27723314  0.27255889  0.47510565]
 [ 0.25004315 -0.41683865  0.38973862 -0.30230622 -0.28310169  0.20302108
  -0.20458311 -0.06285836  0.45152537 -0.02464019]
 [-0.05899192 -0.1542229   0.56018951  0.60821044 -0.35572844 -0.29109733
   0.12010764 -0.04896231 -0.25935299 -0.1201517 ]
 [ 0.19560908 -0.12798738  0.00496045  0.06552803 -0.12770778  0.17276897
  -0.23295833 -0.25175501  0.14138917  0.16015278]
 [-0.21190294 -0.20113419  0.41750034 -0.30725835  0.32280216 -0.33887774
   0.30005164  0.55345384 -0.1046319  -0.43000286]]


#### 59. How to sort an array by the nth column? (★★☆)

In [326]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[6 6 8]
 [5 0 6]
 [0 0 5]]
[[5 0 6]
 [0 0 5]
 [6 6 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [329]:
# null : 0 
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

# null : np.nan
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))

False
[False False  True]


#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [334]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [342]:
Z = np.ones(100)
I = np.random.randint(0,len(Z),20)
np.add.at(Z, I, 1)
print(Z)

[2. 1. 1. 1. 1. 1. 2. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1.
 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1.
 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 3. 2. 1. 1. 1. 2. 1. 2. 1.
 2. 1. 1. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [343]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [346]:
A = np.random.randint(0,10,(3,4,3,4))
print(A)
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print('\n',sum)

[[[[5 1 1 2]
   [0 6 1 3]
   [1 4 5 5]]

  [[9 4 9 2]
   [9 8 3 7]
   [2 2 3 9]]

  [[2 0 0 7]
   [4 4 3 0]
   [8 6 6 6]]

  [[6 9 5 3]
   [7 0 0 9]
   [4 6 0 2]]]


 [[[1 1 6 5]
   [4 0 6 2]
   [2 0 8 3]]

  [[0 6 3 9]
   [7 3 7 9]
   [2 9 0 3]]

  [[9 1 0 3]
   [2 7 4 6]
   [0 2 5 4]]

  [[5 9 7 5]
   [5 0 1 8]
   [0 1 6 7]]]


 [[[2 0 3 6]
   [2 1 2 7]
   [8 8 5 4]]

  [[7 7 3 0]
   [3 4 3 4]
   [0 8 7 4]]

  [[4 0 0 5]
   [6 3 7 5]
   [6 0 1 0]]

  [[8 6 1 1]
   [1 0 9 6]
   [2 9 9 3]]]]

 [[34 67 46 51]
 [38 58 43 54]
 [48 50 37 55]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [348]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
S

array([0, 6, 3, 8, 4, 8, 7, 5, 9, 6, 2, 9, 3, 5, 6, 4, 1, 6, 3, 3, 5, 2,
       5, 6, 4, 4, 7, 6, 8, 9, 5, 6, 5, 9, 4, 4, 8, 9, 1, 6, 0, 5, 9, 3,
       5, 6, 7, 4, 4, 2, 3, 5, 8, 7, 1, 0, 4, 6, 5, 7, 9, 4, 5, 5, 9, 8,
       8, 6, 5, 9, 9, 9, 6, 9, 9, 1, 7, 8, 2, 5, 9, 7, 6, 2, 5, 1, 6, 3,
       3, 2, 6, 9, 6, 3, 0, 4, 2, 4, 7, 6])

#### 69. How to get the diagonal of a dot product? (★★★)

In [351]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

array([1.52285095, 1.8986904 , 1.72443259, 1.31361361, 0.54264729])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [358]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [369]:
A = np.arange(25).reshape(5,5)
print(A,'\n')
A[[0,2]] = A[[2,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [372]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.20899045,  0.91808163, -0.85340813, -0.71729571,  0.33354102,
        0.54737709, -0.20228623,  0.35338885,  0.35294441, -0.6793041 ,
        0.61657217, -0.79846507, -0.83475177,  0.93941252, -0.57643425,
        0.83796124, -0.0292564 , -0.5529616 ,  0.51682399,  0.11660555,
       -0.1492074 ,  0.07251229,  0.58316637,  0.63858762,  0.09578015,
        0.21748066,  0.68900672, -0.40202339,  0.21223643, -0.67425594,
        0.2079778 , -0.37615174, -0.91278071, -0.50004183,  0.79733519,
        0.31441991,  0.25521821,  0.93528055, -0.72721291,  0.43354689,
       -0.78059651,  0.2911741 , -0.76570799,  0.39031269, -0.13224464,
       -0.20762504, -0.7867861 , -0.05631846,  0.17195715, -0.43804861,
        0.51461343,  0.06981729, -0.63456913, -0.67271576,  0.9000423 ,
       -0.73235884, -0.0604509 , -0.06357379,  0.73339671, -0.14190248,
       -0.90468219, -0.36389623,  0.91765104,  0.81597184, -0.41560434,
        0.38541283, -0.25235547,  0.35458578,  0.47844697,  0.30

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [378]:
Z = np.arange(1, 15)
print(sliding_window_view(Z, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [383]:
# Z = np.random.uniform(0,1,(10,10))
# U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
# rank = np.sum(S > 1e-10)
# print(rank)
rank = np.linalg.matrix_rank(Z)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [385]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[4 3 3 5 5 2 0 5 2 3 1 0 2 7 3 6 4 8 7 8 4 5 4 6 3 8 9 0 6 0 6 3 5 6 5 9 4
 5 2 4 0 2 1 4 4 8 9 3 0 1]
4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [388]:
Z = np.ones((16,16))
k = 4

windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))
S

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [400]:
Z = np.arange(1000)
# print(Z)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])

[995 996 997 998 999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)